name = "wee_noise_maker"
description = "Shiny new project"
version = "0.0.0"

authors = ["Fabien Chouteau"]
maintainers = ["Fabien Chouteau <fabien.chouteau@gmail.com>"]
maintainers-logins = ["Fabien-Chouteau"]

executables = ["wee_noise_maker"]
[[depends-on]]
rp2040_hal = "~0.6.0"
gnat_arm_elf = "^11.2.2"

[[pins]]
rp2040_hal = { path='../../../JeremyGrosser/rp2040_hal' }

[configuration.values]
rp2040_hal.Flash_Chip = "generic_qspi"
[[depends-on]]  # Added by alr
littlefs = "~0.1.0"  # Added by alr
