name = "wee_noise_maker_sim"
description = "Shiny new project"
version = "0.0.0"

authors = ["Fabien Chouteau"]
maintainers = ["Fabien Chouteau <chouteau@adacore.com>"]
maintainers-logins = ["Fabien-Chouteau"]

executables = ["wee_noise_maker_sim"]

[[depends-on]]
hal = "*"
littlefs = "*"
bbqueue = "*"
virtapu = "*"
asfml = "*"
